### ISSUE TITLE
Public keys are world-writeable

### ISSUE THREAD

**Issue by stef** [privacybydesign/gabi#6]
In file keys.go:315 in the function `func (pubk *PublicKey) WriteToFile(filename string, forceOverwrite bool) (int64, error)`

```
    os.OpenFile(filename, os.O_RDWR|os.O_CREATE|os.O_EXCL, 0666)
```
This makes it trivially easy for an attacker to change the public keys to some values controlled by them.

Recommendation: change this to `0644`.

**Comment by sietseringers** [comment]
Fixed in #11.
